- name: setup application instance
  remote_user: ubuntu
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes

    - name: install dependencies
      apt:
        name:
          - go1.11.2.linux-amd64
        state: present

  pre_tasks:        
    - name: 'install postgres'
      raw: sudo apt install -y postgresql postgresql-contrib